[package]
name = "json5"
version = "0.1.0"
authors = ["Callum Oakley <c.oakley108@gmail.com>"]

[dependencies]
pest = { git = "https://github.com/pest-parser/pest" }
pest_derive = { git = "https://github.com/pest-parser/pest" }
serde = "1.0"

[dev-dependencies]
serde_derive = "1.0"
